Aeneta/urls.py
from django.contrib import admin
from django.urls import path, include
from usuarios.views import CustomLoginView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('usuarios/', include(('usuarios.urls', 'usuarios'), namespace='usuarios')),  # Incluye las URLs de la aplicación usuarios
    path('', CustomLoginView.as_view(), name='login'),  # El path vacío redirige al login
    path('administracion/', include('administracion.urls', namespace='administracion')),  # Incluye las URLs con el namespace
    path('alumnos/', include('alumnos.urls', namespace='alumnos')),
    path('visitante/', include(('visitante.urls', 'visitante'), namespace='visitante')),
    path('docente/', include('docente.urls', namespace='docente')),
    # ... cualquier otra ruta que necesites ...
]

visitante/urls.py
# visitante/urls.py
from django.urls import path
from .views import VisitanteHomeView, VisitanteCbuscarView, VisitanteContactoView, VisitantePfrecuentesView, VisitanteBuscarView

app_name = 'visitante'

urlpatterns = [
    path('home/', VisitanteHomeView.as_view(), name='home'),
    path('buscar/', VisitanteBuscarView.as_view(), name='buscar'), 
    path('como_buscar/', VisitanteCbuscarView.as_view(), name='como_buscar'),  
    path('preguntas_frecuentes/', VisitantePfrecuentesView.as_view(), name='preguntas_frecuentes'),  
    path('contactanos/', VisitanteContactoView.as_view(), name='contactanos')  
   # ... más patrones de URL ...
]

visitante/models.py
from django.db import models

# Create your models here.

visitante/views.py
from django.views.generic import TemplateView

class VisitanteHomeView(TemplateView):
    template_name = 'visitante/home.html'

class VisitanteBuscarView(TemplateView): 
    template_name = 'visitante/buscar.html'

class VisitanteCbuscarView(TemplateView): 
    template_name = 'visitante/como_buscar.html'

class VisitantePfrecuentesView(TemplateView): 
    template_name = 'visitante/preguntas_frecuentes.html'

class VisitanteContactoView(TemplateView): 
    template_name = 'visitante/contactanos.html'

visitante/templates/base_generic_visitante.html
<!DOCTYPE html>
{% load static %}
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Página de Visitantes</title>
    <link rel="stylesheet" type="text/css" href="{% static 'styles/home.css' %}">
</head>
<body>
    <div id="nombre_sistema" class="header-flex-container">
        <a href="{% url 'visitante:home' %}">
            <span>Repositorio Aeneta</span>
        </a>
        <a id="iniciar" href="{% url 'usuarios:login' %}">Iniciar sesión</a>
      </div>
      <nav class="nav_bar" aria-label="Navegación principal">
        <a class="nav-link" href="{% url 'visitante:buscar' %}">Realizar búsqueda</a>
        <a class="nav-link" href="{% url 'visitante:como_buscar' %}" >¿Cómo buscar?</a>
        <a class="nav-link" href="{% url 'visitante:preguntas_frecuentes' %}" >Preguntas frecuentes</a>
        <a class="nav-link" href="{% url 'visitante:contactanos' %}" >Contáctanos</a>
      </nav>
    {% block content %}
   
    {% endblock %}
    <footer>
        <p>Aeneta - Tiburones 2024 ©</p>
    </footer>
</body>
</html>