Aeneta/urls.py
from django.contrib import admin
from django.urls import path, include
from usuarios.views import CustomLoginView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('usuarios/', include(('usuarios.urls', 'usuarios'), namespace='usuarios')),  # Incluye las URLs de la aplicación usuarios
    path('', CustomLoginView.as_view(), name='login'),  # El path vacío redirige al login
    path('administracion/', include('administracion.urls', namespace='administracion')),  # Incluye las URLs con el namespace
    path('alumnos/', include('alumnos.urls', namespace='alumnos')),
    path('visitante/', include(('visitante.urls', 'visitante'), namespace='visitante')),
    path('docente/', include('docente.urls', namespace='docente')),
    # ... cualquier otra ruta que necesites ...
]

alumnos/urls.py
# alumnos/urls.py
from django.urls import path
from .views import AlumnosHomeView

app_name = 'alumnos'

urlpatterns = [
    path('home/', AlumnosHomeView.as_view(), name='home'),
    # ... más patrones de URL ...
]

usuarios/urls.py
from django.urls import path
from .views import SignUpView
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    #path('login/', auth_views.LoginView.as_view(), name='login'),
    path('login/', views.CustomLoginView.as_view(), name='login'),
    path('signup/', SignUpView.as_view(), name='signup'),
    # Asegúrate de que la URL de login esté incluida también
    # ...
]

usuarios/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class CustomUser(AbstractUser):
    # Campos generales
    nombre = models.CharField(max_length=100)
    apellido = models.CharField(max_length=100)
    correo_electronico = models.EmailField(unique=True)
    
    # Campos específicos por tipo de usuario
    is_administrador = models.BooleanField(default=False)
    is_alumno = models.BooleanField(default=False)
    is_docente = models.BooleanField(default=False)
    
    # Alumno
    matricula = models.CharField(max_length=20, blank=True, null=True)
    programa_academico = models.CharField(max_length=100, blank=True, null=True)
    estatus = models.CharField(max_length=20, choices=[('activo', 'Activo'), ('egresado', 'Egresado')], blank=True, null=True)
    
    # Docente
    especialidad = models.CharField(max_length=100, blank=True, null=True)
    departamento_docente = models.CharField(max_length=100, blank=True, null=True)
    
    # Administrativo
    cargo = models.CharField(max_length=100, blank=True, null=True)
    departamento_admin = models.CharField(max_length=100, blank=True, null=True)

usuarios/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):
    # Campos generales
    nombre = forms.CharField(max_length=100, required=True)
    apellido = forms.CharField(max_length=100, required=True)
    correo_electronico = forms.EmailField(required=True)
    
    # Añade los campos de radio con las nuevas opciones
    user_type = forms.ChoiceField(
        choices=[
            ('is_administrador', 'Administrador'), 
            ('is_alumno', 'Alumno'),
            ('is_docente', 'Docente')
        ],
        widget=forms.RadioSelect,
        required=True
    )
    
    matricula = forms.CharField(max_length=20, required=False)
    programa_academico = forms.CharField(max_length=100, required=False)
    estatus = forms.ChoiceField(choices=[('activo', 'Activo'), ('egresado', 'Egresado')], required=False)
    especialidad = forms.CharField(max_length=100, required=False)
    departamento_docente = forms.CharField(max_length=100, required=False)
    cargo = forms.CharField(max_length=100, required=False)
    departamento_admin = forms.CharField(max_length=100, required=False)
    
    class Meta(UserCreationForm.Meta):
        model = CustomUser
        fields = UserCreationForm.Meta.fields + ('nombre', 'apellido', 'correo_electronico', 'user_type', 
                                                  'matricula', 'programa_academico', 'estatus',
                                                  'especialidad', 'departamento_docente',
                                                  'cargo', 'departamento_admin',)
    
    def save(self, commit=True):
        user = super().save(commit=False)
        user.nombre = self.cleaned_data['nombre']
        user.apellido = self.cleaned_data['apellido']
        user.correo_electronico = self.cleaned_data['correo_electronico']
        user_type = self.cleaned_data['user_type']
        
        # Campos específicos por tipo de usuario
        if user_type == 'is_administrador':
            user.is_administrador = True
            user.cargo = self.cleaned_data['cargo']
            user.departamento_admin = self.cleaned_data['departamento_admin']
        elif user_type == 'is_alumno':
            user.is_alumno = True
            user.matricula = self.cleaned_data['matricula']
            user.programa_academico = self.cleaned_data['programa_academico']
            user.estatus = self.cleaned_data['estatus']
        elif user_type == 'is_docente':
            user.is_docente = True
            user.especialidad = self.cleaned_data['especialidad']
            user.departamento_docente = self.cleaned_data['departamento_docente']
        
        if commit:
            user.save()
        return user

usuarios/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import generic
from .forms import CustomUserCreationForm
from django.contrib.auth.views import LoginView
from django.shortcuts import resolve_url

class SignUpView(generic.CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'usuarios/signup.html'

class CustomLoginView(LoginView):
    template_name = 'usuarios/login.html'  # Especifica la ubicación del template de login

    def get_success_url(self):
        # Lógica para redirigir a diferentes usuarios a diferentes páginas
        if self.request.user.is_administrador:
            return resolve_url('administracion:home')
        elif self.request.user.is_alumno:
            return resolve_url('alumnos:home')
        elif self.request.user.is_docente:
            return resolve_url('docente:home')
        #elif self.request.user.is_visitante:
            #return resolve_url('visitante:home')
        else:
            return resolve_url('url_por_defecto')

usuarios/templates/usuarios/login.html
{% extends 'base_generic.html' %}

{% block content %}
<div class="login-container">  
  <div class="login-form">
    <h1>Login</h1>
    <form method="post" action="{% url 'login' %}">
      {% csrf_token %}
      <div class="form-group">
        <input type="text" name="username" class="form-control" placeholder="Usuario">
      </div>
      <div class="form-group">
        <input type="password" name="password" class="form-control" placeholder="Contraseña">
      </div>
      <button type="submit" class="button">Ingresar</button>
    </form>
    <p class="sign-up-link">¿No tienes cuenta?  <a href="{% url 'visitante:home' %}">Ingresar como invitado</a></p>
    <p class="sign-up-link">Quitar  <a href="{% url 'usuarios:signup' %}">Formulario</a></p>
  </div>
</div>
{% endblock %}

usuarios/templates/usuarios/signup.html
{% extends 'base_generic.html' %}

{% block content %}
<h2>Sign up</h2>
<form method="post" id="signupForm">
  {% csrf_token %}
  {{ form.non_field_errors }}
  
  {{ form.nombre.label_tag }} {{ form.nombre }}
  {{ form.apellido.label_tag }} {{ form.apellido }}
  {{ form.correo_electronico.label_tag }} {{ form.correo_electronico }}

  {{ form.username.label_tag }} {{ form.username }} {{ form.username.errors }}
  {{ form.password1.label_tag }} {{ form.password1 }} {{ form.password1.errors }}
  {{ form.password2.label_tag }} {{ form.password2 }} {{ form.password2.errors }}

  {{ form.user_type.label_tag }} {{ form.user_type }}

  <!-- Campos para Alumnos -->
  <div id="alumnoFields" style="display: none;">
    {{ form.matricula.label_tag }} {{ form.matricula }}
    {{ form.programa_academico.label_tag }} {{ form.programa_academico }}
    {{ form.estatus.label_tag }} {{ form.estatus }}
  </div>

  <!-- Campos para Docentes -->
  <div id="docenteFields" style="display: none;">
    {{ form.especialidad.label_tag }} {{ form.especialidad }}
    {{ form.departamento_docente.label_tag }} {{ form.departamento_docente }}
  </div>

  <!-- Campos para Administrativos -->
  <div id="administrativoFields" style="display: none;">
    {{ form.cargo.label_tag }} {{ form.cargo }}
    {{ form.departamento_admin.label_tag }} {{ form.departamento_admin }}
  </div>

  <button type="submit">Register</button>
</form>

<script>
document.addEventListener('DOMContentLoaded', function () {
  const userTypeFields = document.querySelectorAll('input[name="user_type"]');
  
  userTypeFields.forEach(function(userTypeField) {
    userTypeField.addEventListener('change', function (e) {
      const selectedType = e.target.value;
      document.getElementById('alumnoFields').style.display = selectedType === 'is_alumno' ? 'block' : 'none';
      document.getElementById('docenteFields').style.display = selectedType === 'is_docente' ? 'block' : 'none';
      document.getElementById('administrativoFields').style.display = selectedType === 'is_administrador' ? 'block' : 'none';
    });
  });
});

</script>
{% endblock %}